### ISSUE TITLE
On "find friends" page, behaviour is erratic

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-plugin-friends#1]
- Clicking on "Add Friend" changes the button to "Remove Friend"
  - Expected "Friend Request Sent" or some other related text copy
- When friend request is pending, loading the find friends page shows the text "Add Friend"
  - Expected "Friend Request Sent" or some other related text copy

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-h2w-atkins/commit/ac2a136d11b86cd0b28de58a0129e4c46e1a4e5c
