### ISSUE TITLE
Can rejectFriendship be simplified?

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-plugin-friends#3]
https://github.com/NodeBB/nodebb-plugin-friends/blob/master/lib/friends.js#L113-L124

Given that the calls here are a subset of removeFriendship, and rejection only happens when users are _expicitly_ **not** friends, then I'd think that rejectFriendship should just call removeFriendship, and fire off the corresponding hook in its callback.

**Comment by barisusakli** [comment]
Well this is easy to do but you wont be able to tell if someone is rejecting a friend request or just unfriending someone.

**Comment by julianlam** [comment]
via hook? I think you could, if rejectFriendship just called removeFriendship, and in its callback, fired off its own hook... (then again, it means you get double-hooks, so maybe not)

Nevermind.
